import { useEffect, useState } from 'react'
import { CheckCircle2, ClipboardCheck } from 'lucide-react'
import { expertApi } from '../../services/api'

export default function ExpertQueue() {
  const [reviews, setReviews] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ verdict: 'confirmed', correctedConditionId: null, severity: 'medium', notes: '' }); const [message, setMessage] = useState('')
  const load = () => expertApi.queue().then((response) => setReviews(response.data)); useEffect(load, [])
  const submit = async (event) => { event.preventDefault(); await expertApi.submit({ reviewId: selected.id, ...form, correctedConditionId: form.verdict === 'corrected' ? form.correctedConditionId : null }); setMessage('Review submitted and farmer notified.'); setSelected(null); load() }
  return <div><h1 className="text-3xl font-semibold">Assigned expert cases</h1><p className="muted mt-1">Only cases explicitly assigned to your verified account appear here.</p>{reviews.length === 0 ? <div className="surface p-10 mt-6 text-center muted"><ClipboardCheck className="w-9 mx-auto mb-2" />No assigned cases.</div> : <div className="grid md:grid-cols-2 gap-4 mt-6">{reviews.map((review) => <button key={review.id} className="surface p-5 text-left" onClick={() => setSelected(review)}><p className="font-semibold">Scan {review.scanId}</p><p className="text-sm muted mt-1">District: {review.district || 'Withheld'} · Status: {review.status}</p></button>)}</div>}
    {selected && <form className="surface p-5 mt-6" onSubmit={submit}><h2 className="font-semibold">Review {selected.scanId}</h2><div className="grid sm:grid-cols-2 gap-4 mt-4"><label className="field-label">Verdict<select className="field mt-1" value={form.verdict} onChange={(e) => setForm({ ...form, verdict: e.target.value })}><option value="confirmed">Confirm model result</option><option value="corrected">Correct result</option><option value="inconclusive">Inconclusive</option></select></label><label className="field-label">Severity<select className="field mt-1" value={form.severity} onChange={(e) => setForm({ ...form, severity: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div>{form.verdict === 'corrected' && <input className="field mt-4" placeholder="Correct condition ID" required onChange={(e) => setForm({ ...form, correctedConditionId: e.target.value })} />}<textarea className="field mt-4" rows="5" placeholder="Evidence, management guidance, and escalation notes" maxLength="2000" required value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><button className="primary-button mt-4"><CheckCircle2 className="w-4" /> Complete signed review</button></form>}{message && <p className="mt-4">{message}</p>}
  </div>
}
