import { createContext, useContext, useMemo, useState } from 'react'

const common = {
  en: { dashboard:'Dashboard', farms:'Farms', history:'History', alerts:'Alerts', scan:'Scan crop', settings:'Settings', logout:'Log out', theme:'Theme', language:'Language', light:'Light', dark:'Dark', system:'System', close:'Close', retry:'Retry', loading:'Loading…', saving:'Saving…', protectedGuidance:'AI-assisted guidance. Confirm uncertain or serious cases with an agricultural expert.', unableDiagnose:'Unable to diagnose reliably', expertReview:'Request expert review', goodDay:'Good day, {name} 👋', dashboardSubtitle:'Secure crop monitoring and expert-backed escalation.', totalFarms:'Total farms', totalScans:'Total scans', healthyResults:'Healthy results', needsAttention:'Needs attention', recentScans:'Recent scans', noScansDashboard:'No scans yet. Scan your first leaf to see AI results here.', scanACrop:'Scan a crop', yourFarms:'Your farms', noFarms:'No farms yet.', addFirstFarm:'+ Add your first farm', confidence:'confidence', pending:'Pending', dashboardLoadError:'Some dashboard data could not be loaded.', myFarms:'My farms', coordinatesPrivate:'Exact coordinates remain private.', addFarm:'Add farm', farmDetails:'Farm details', farmName:'Farm name', district:'District', taluka:'Taluka', village:'Village', areaAcres:'Area (acres)', soilType:'Soil type', irrigation:'Irrigation', weatherLocation:'Weather location', useGps:'Use approximate GPS', locationCaptured:'Captured with consent', saveFarm:'Save private farm', loadingFarms:'Loading your farms securely…', farmsLoadError:'Your farms could not be loaded.', farmSaveError:'Farm could not be saved.', farmDeleteError:'Farm could not be deleted.', gpsUnavailable:'GPS is not available in this browser.', locationDenied:'Location permission was not granted. Village entry is enough to continue.', deleteFarmConfirm:'Delete {name}? Active crop records must be archived first.', deleteFarm:'Delete {name}', locationNotAdded:'Location not added', area:'Area', acres:'acres', soil:'Soil', historyTitle:'Crop health history', allSeverities:'All severities', healthy:'Healthy', low:'Low', medium:'Medium', high:'High', noHistory:'No scans yet. Once you scan crops, trends and charts will appear here.', historyLoadError:'Crop history could not be loaded.', date:'Date', disease:'Disease', severity:'Severity' },
  mr: { dashboard:'डॅशबोर्ड', farms:'शेती', history:'इतिहास', alerts:'सूचना', scan:'पीक तपासा', settings:'सेटिंग्ज', logout:'बाहेर पडा', theme:'थीम', language:'भाषा', light:'प्रकाश', dark:'गडद', system:'सिस्टम', close:'बंद करा', retry:'पुन्हा प्रयत्न करा', loading:'लोड होत आहे…', saving:'जतन होत आहे…', protectedGuidance:'हे AI-सहाय्यित मार्गदर्शन आहे. अनिश्चित किंवा गंभीर प्रकरण तज्ज्ञांकडून तपासा.', unableDiagnose:'विश्वसनीय निदान करता आले नाही', expertReview:'तज्ज्ञ पुनरावलोकन मागा', goodDay:'नमस्कार, {name} 👋', dashboardSubtitle:'सुरक्षित पीक निरीक्षण आणि तज्ज्ञांची मदत.', totalFarms:'एकूण शेतं', totalScans:'एकूण तपासण्या', healthyResults:'निरोगी निकाल', needsAttention:'लक्ष देणे आवश्यक', recentScans:'अलीकडील तपासण्या', noScansDashboard:'अजून तपासणी नाही. AI निकालासाठी पहिले पान तपासा.', scanACrop:'पीक तपासा', yourFarms:'तुमची शेतं', noFarms:'अजून शेत जोडलेले नाही.', addFirstFarm:'+ पहिले शेत जोडा', confidence:'विश्वास', pending:'प्रलंबित', dashboardLoadError:'डॅशबोर्डचा काही डेटा लोड झाला नाही.', myFarms:'माझी शेतं', coordinatesPrivate:'अचूक स्थान खाजगी ठेवले जाते.', addFarm:'शेत जोडा', farmDetails:'शेताची माहिती', farmName:'शेताचे नाव', district:'जिल्हा', taluka:'तालुका', village:'गाव', areaAcres:'क्षेत्रफळ (एकर)', soilType:'मातीचा प्रकार', irrigation:'सिंचन', weatherLocation:'हवामान स्थान', useGps:'अंदाजे GPS वापरा', locationCaptured:'संमतीने स्थान घेतले', saveFarm:'शेत सुरक्षित जतन करा', loadingFarms:'तुमची शेतं सुरक्षितपणे लोड होत आहेत…', farmsLoadError:'तुमची शेतं लोड झाली नाहीत.', farmSaveError:'शेत जतन करता आले नाही.', farmDeleteError:'शेत हटवता आले नाही.', gpsUnavailable:'या ब्राउझरमध्ये GPS उपलब्ध नाही.', locationDenied:'स्थानाची परवानगी मिळाली नाही. गावाची माहिती पुरेशी आहे.', deleteFarmConfirm:'{name} हटवायचे? सक्रिय पीक नोंदी आधी संग्रहित करा.', deleteFarm:'{name} हटवा', locationNotAdded:'स्थान जोडलेले नाही', area:'क्षेत्रफळ', acres:'एकर', soil:'माती', historyTitle:'पीक आरोग्य इतिहास', allSeverities:'सर्व तीव्रता', healthy:'निरोगी', low:'कमी', medium:'मध्यम', high:'जास्त', noHistory:'अजून तपासणी नाही. तपासणीनंतर आलेख येथे दिसतील.', historyLoadError:'पीक इतिहास लोड झाला नाही.', date:'तारीख', disease:'रोग', severity:'तीव्रता' },
  hi: { dashboard:'डैशबोर्ड', farms:'खेत', history:'इतिहास', alerts:'अलर्ट', scan:'फसल स्कैन करें', settings:'सेटिंग्स', logout:'लॉग आउट', theme:'थीम', language:'भाषा', light:'लाइट', dark:'डार्क', system:'सिस्टम', close:'बंद करें', retry:'फिर कोशिश करें', loading:'लोड हो रहा है…', saving:'सहेजा जा रहा है…', protectedGuidance:'यह AI-सहायित मार्गदर्शन है। अनिश्चित या गंभीर मामले की विशेषज्ञ से पुष्टि करें।', unableDiagnose:'विश्वसनीय निदान नहीं हो सका', expertReview:'विशेषज्ञ समीक्षा माँगें', goodDay:'नमस्ते, {name} 👋', dashboardSubtitle:'सुरक्षित फसल निगरानी और विशेषज्ञ सहायता।', totalFarms:'कुल खेत', totalScans:'कुल स्कैन', healthyResults:'स्वस्थ परिणाम', needsAttention:'ध्यान आवश्यक', recentScans:'हाल के स्कैन', noScansDashboard:'अभी कोई स्कैन नहीं। AI परिणाम के लिए पहला पत्ता स्कैन करें।', scanACrop:'फसल स्कैन करें', yourFarms:'आपके खेत', noFarms:'अभी कोई खेत नहीं।', addFirstFarm:'+ पहला खेत जोड़ें', confidence:'विश्वास', pending:'लंबित', dashboardLoadError:'डैशबोर्ड का कुछ डेटा लोड नहीं हुआ।', myFarms:'मेरे खेत', coordinatesPrivate:'सटीक स्थान निजी रखा जाता है।', addFarm:'खेत जोड़ें', farmDetails:'खेत का विवरण', farmName:'खेत का नाम', district:'जिला', taluka:'तालुका', village:'गाँव', areaAcres:'क्षेत्र (एकड़)', soilType:'मिट्टी का प्रकार', irrigation:'सिंचाई', weatherLocation:'मौसम स्थान', useGps:'अनुमानित GPS उपयोग करें', locationCaptured:'सहमति से स्थान लिया गया', saveFarm:'खेत सुरक्षित सहेजें', loadingFarms:'आपके खेत सुरक्षित रूप से लोड हो रहे हैं…', farmsLoadError:'आपके खेत लोड नहीं हो सके।', farmSaveError:'खेत सहेजा नहीं जा सका।', farmDeleteError:'खेत हटाया नहीं जा सका।', gpsUnavailable:'इस ब्राउज़र में GPS उपलब्ध नहीं है।', locationDenied:'स्थान की अनुमति नहीं मिली। गाँव की जानकारी पर्याप्त है।', deleteFarmConfirm:'{name} हटाएँ? सक्रिय फसल रिकॉर्ड पहले संग्रहित करें।', deleteFarm:'{name} हटाएँ', locationNotAdded:'स्थान नहीं जोड़ा गया', area:'क्षेत्र', acres:'एकड़', soil:'मिट्टी', historyTitle:'फसल स्वास्थ्य इतिहास', allSeverities:'सभी गंभीरताएँ', healthy:'स्वस्थ', low:'कम', medium:'मध्यम', high:'उच्च', noHistory:'अभी कोई स्कैन नहीं। स्कैन के बाद चार्ट यहाँ दिखेंगे।', historyLoadError:'फसल इतिहास लोड नहीं हुआ।', date:'तारीख', disease:'रोग', severity:'गंभीरता' },
}

const scanMessages = {
  en: { scanTitle:'Guided crop diagnosis', scanSubtitle:'Two views and symptom context reduce unsafe guesses.', privateImages:'Private images', selectCropStep:'1. Select crop', farm:'Farm', selectFarm:'Select farm', activeCrop:'Active crop', selectPlantedCrop:'Select planted crop', addCropToFarm:'Add crop to farm…', add:'Add', weatherRisk:'Check weather risk', captureEvidence:'2. Capture evidence', affectedCloseup:'Affected area close-up', closeupHelp:'Keep the lesion or pest in focus.', wholePlant:'Whole plant', wholePlantHelp:'Include healthy and affected parts.', fieldContext:'Field context', fieldContextHelp:'Optional wider view.', symptomsStep:'3. Symptoms', affectedArea:'Affected area', notSure:'Not sure', fewLeaves:'Few leaves', manyLeaves:'Many leaves', wholePlantOption:'Whole plant', spreadSpeed:'Spread speed', slow:'Slow', fast:'Fast', visiblePests:'Visible pests', none:'None', few:'Few', many:'Many', observations:'Additional observations', submitAnalysis:'Submit for analysis', processingSecurely:'Processing securely…', reference:'Reference' },
  mr: { scanTitle:'मार्गदर्शित पीक निदान', scanSubtitle:'दोन छायाचित्रे आणि लक्षणांची माहिती अधिक सुरक्षित निकाल देतात.', privateImages:'खाजगी छायाचित्रे', selectCropStep:'१. पीक निवडा', farm:'शेत', selectFarm:'शेत निवडा', activeCrop:'सक्रिय पीक', selectPlantedCrop:'लावलेले पीक निवडा', addCropToFarm:'शेतात पीक जोडा…', add:'जोडा', weatherRisk:'हवामान धोका तपासा', captureEvidence:'२. छायाचित्रे घ्या', affectedCloseup:'बाधित भाग जवळून', closeupHelp:'डाग किंवा कीड फोकसमध्ये ठेवा.', wholePlant:'संपूर्ण रोप', wholePlantHelp:'निरोगी आणि बाधित भाग समाविष्ट करा.', fieldContext:'शेताचा परिसर', fieldContextHelp:'ऐच्छिक विस्तृत दृश्य.', symptomsStep:'३. लक्षणे', affectedArea:'बाधित क्षेत्र', notSure:'माहित नाही', fewLeaves:'काही पाने', manyLeaves:'अनेक पाने', wholePlantOption:'संपूर्ण रोप', spreadSpeed:'प्रसाराचा वेग', slow:'हळू', fast:'जलद', visiblePests:'दिसणारी कीड', none:'नाही', few:'थोडी', many:'अनेक', observations:'अतिरिक्त निरीक्षणे', submitAnalysis:'विश्लेषणासाठी पाठवा', processingSecurely:'सुरक्षित प्रक्रिया सुरू आहे…', reference:'संदर्भ' },
  hi: { scanTitle:'निर्देशित फसल निदान', scanSubtitle:'दो तस्वीरें और लक्षणों की जानकारी अधिक सुरक्षित परिणाम देती हैं।', privateImages:'निजी तस्वीरें', selectCropStep:'1. फसल चुनें', farm:'खेत', selectFarm:'खेत चुनें', activeCrop:'सक्रिय फसल', selectPlantedCrop:'लगाई गई फसल चुनें', addCropToFarm:'खेत में फसल जोड़ें…', add:'जोड़ें', weatherRisk:'मौसम जोखिम जाँचें', captureEvidence:'2. तस्वीरें लें', affectedCloseup:'प्रभावित भाग पास से', closeupHelp:'दाग या कीट को फोकस में रखें।', wholePlant:'पूरा पौधा', wholePlantHelp:'स्वस्थ और प्रभावित भाग शामिल करें।', fieldContext:'खेत का संदर्भ', fieldContextHelp:'वैकल्पिक विस्तृत दृश्य।', symptomsStep:'3. लक्षण', affectedArea:'प्रभावित क्षेत्र', notSure:'पता नहीं', fewLeaves:'कुछ पत्ते', manyLeaves:'कई पत्ते', wholePlantOption:'पूरा पौधा', spreadSpeed:'फैलने की गति', slow:'धीमी', fast:'तेज़', visiblePests:'दिखने वाले कीट', none:'कोई नहीं', few:'कुछ', many:'कई', observations:'अतिरिक्त जानकारी', submitAnalysis:'विश्लेषण के लिए भेजें', processingSecurely:'सुरक्षित प्रक्रिया जारी है…', reference:'संदर्भ' },
}

const I18nContext = createContext(null)
export function I18nProvider({ children }) {
  const [locale, setLocaleState] = useState(() => localStorage.getItem('cropai_language') || 'en')
  const setLocale = (value) => { if (!common[value]) return; localStorage.setItem('cropai_language', value); document.documentElement.lang = value; setLocaleState(value) }
  const value = useMemo(() => ({ locale, setLocale, t: (key, values = {}) => {
    const message = common[locale]?.[key] || scanMessages[locale]?.[key] || common.en[key] || scanMessages.en[key] || key
    return message.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`)
  } }), [locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export const useI18n = () => useContext(I18nContext)
