import { useEffect, useState } from 'react'
import { ShieldCheck, UserCheck, UserX } from 'lucide-react'
import { adminApi } from '../../services/api'

export default function AdminDashboard() {
  const [requests, setRequests] = useState([]); const [outbreaks, setOutbreaks] = useState([]); const [message, setMessage] = useState(''); const load = () => Promise.all([adminApi.pendingExperts(), adminApi.outbreaks()]).then(([requestsResponse, outbreakResponse]) => { setRequests(requestsResponse.data); setOutbreaks(outbreakResponse.data) }); useEffect(load, [])
  const decide = async (uid, approved) => { await adminApi.approveExpert(uid, approved, approved ? 'Credentials verified by administrator' : 'Credentials could not be verified'); setMessage(approved ? 'Expert approved. New claims apply after token refresh.' : 'Request rejected.'); load() }
  return <div><h1 className="text-3xl font-semibold">Administration</h1><p className="muted mt-1">Privileged actions are enforced and audited server-side.</p><div className="surface p-5 mt-6"><h2 className="font-semibold flex items-center gap-2"><ShieldCheck className="w-5" /> Pending expert verification</h2>{requests.length === 0 ? <p className="muted text-sm mt-4">No pending requests.</p> : <div className="divide-y divide-[var(--border)] mt-4">{requests.map((request) => <div key={request.id} className="py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-semibold">{request.organization}</p><p className="text-sm muted">{request.qualification} · {request.registrationNumber}</p></div><div className="flex gap-2"><button className="primary-button" onClick={() => decide(request.uid, true)}><UserCheck className="w-4" /> Approve</button><button className="danger-button" onClick={() => decide(request.uid, false)}><UserX className="w-4 mr-1" /> Reject</button></div></div>)}</div>}</div><section className="mt-6"><h2 className="font-semibold">Privacy-preserving 7-day outbreak signals</h2><p className="text-sm muted mt-1">District groups with fewer than five scans are suppressed.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">{outbreaks.map((item) => <article key={item.id} className="surface p-4" style={{ borderLeft: `6px solid color-mix(in srgb, var(--primary) ${Math.min(item.total * 8, 100)}%, var(--border))` }}><p className="font-semibold">{item.district}</p><p className="text-sm muted">{item.total} validated signals · {item.period}</p><ul className="text-xs mt-2">{Object.entries(item.conditions || {}).map(([condition, count]) => <li key={condition}>{condition}: {count}</li>)}</ul></article>)}</div></section>{message && <p className="mt-4 surface !shadow-none p-3">{message}</p>}</div>
}
