import { useState } from 'react'
import { Download, ShieldAlert, Trash2 } from 'lucide-react'
import { expertApi, notificationApi, profileApi } from '../../services/api'
import { useI18n } from '../../context/I18nContext'
import { useAuth } from '../../context/AuthContext'

export default function Settings() {
  const { user, startMfaEnrollment, completeMfaEnrollment } = useAuth(); const [message, setMessage] = useState(''); const [expert, setExpert] = useState({ qualification: '', registrationNumber: '', organization: '' }); const [confirm, setConfirm] = useState(''); const [mfaPhone, setMfaPhone] = useState('+91'); const [mfaCode, setMfaCode] = useState(''); const [mfaSent, setMfaSent] = useState(false)
  const { locale } = useI18n()
  const exportData = async () => { const response = await profileApi.export(); const blob = new Blob([JSON.stringify(response.data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'cropai-data-export.json'; link.click(); URL.revokeObjectURL(url) }
  const requestExpert = async (event) => { event.preventDefault(); await expertApi.requestVerification(expert); setMessage('Expert verification request submitted for administrator review.') }
  const remove = async () => { if (confirm !== 'DELETE') return; await profileApi.remove(); window.location.assign('/') }
  return <div className="max-w-3xl"><h1 className="text-3xl font-semibold">Privacy and account</h1><p className="muted mt-1">Control your data, consent and trusted access.</p>
    <section className="surface p-5 mt-6"><h2 className="font-semibold">Your information</h2><dl className="grid sm:grid-cols-2 gap-3 mt-4 text-sm"><div><dt className="muted">Name</dt><dd>{user?.name}</dd></div><div><dt className="muted">Account type</dt><dd className="capitalize">{user?.role}</dd></div><div><dt className="muted">District</dt><dd>{user?.district || 'Not set'}</dd></div><div><dt className="muted">Phone</dt><dd>{user?.phone || 'Protected email account'}</dd></div></dl><div className="flex flex-wrap gap-2 mt-5"><button onClick={exportData} className="secondary-button"><Download className="w-4" /> Export my data</button><button onClick={() => notificationApi.enable(locale).then(() => setMessage('Secure push notifications enabled.')).catch((error) => setMessage(error.message))} className="secondary-button">Enable push alerts</button></div></section>
    {user?.role === 'farmer' && user?.expertVerificationStatus !== 'approved' && <section className="surface p-5 mt-6"><h2 className="font-semibold">Agricultural expert verification</h2><p className="text-sm muted mt-1">Submitting this form does not grant access. An administrator must verify credentials.</p><form className="grid gap-3 mt-4" onSubmit={requestExpert}><input className="field" placeholder="Qualification" maxLength="250" required value={expert.qualification} onChange={(e) => setExpert({ ...expert, qualification: e.target.value })} /><input className="field" placeholder="Registration or credential number" maxLength="100" required value={expert.registrationNumber} onChange={(e) => setExpert({ ...expert, registrationNumber: e.target.value })} /><input className="field" placeholder="Organization" maxLength="250" required value={expert.organization} onChange={(e) => setExpert({ ...expert, organization: e.target.value })} /><button className="primary-button justify-self-start">Request verification</button></form></section>}
    {user?.email && <section className="surface p-5 mt-6"><h2 className="font-semibold">Privileged-account MFA</h2><p className="text-sm muted mt-1">Expert approval is blocked until verified email and a second factor are enrolled.</p><div className="flex flex-col sm:flex-row gap-3 mt-4"><input className="field" value={mfaSent ? mfaCode : mfaPhone} onChange={(e) => mfaSent ? setMfaCode(e.target.value.replace(/\D/g, '')) : setMfaPhone(e.target.value)} placeholder={mfaSent ? '6-digit code' : '+91 mobile number'} /><button className="secondary-button" onClick={() => { if (!mfaSent) startMfaEnrollment(mfaPhone).then(() => setMfaSent(true)).catch((error) => setMessage(error.message)); else completeMfaEnrollment(mfaCode).then(() => { setMfaSent(false); setMessage('MFA enrolled successfully.') }).catch((error) => setMessage(error.message)) }}>{mfaSent ? 'Confirm MFA' : 'Enroll MFA'}</button></div><div id="mfa-enrollment-recaptcha" /></section>}
    <section className="surface p-5 mt-6 border-red-300"><h2 className="font-semibold flex items-center gap-2"><ShieldAlert className="w-5 text-red-600" /> Delete account</h2><p className="text-sm muted mt-1">This permanently deletes your profile, farms, scans, private images, alerts and authentication account.</p><div className="flex flex-col sm:flex-row gap-3 mt-4"><input className="field" placeholder="Type DELETE" value={confirm} onChange={(e) => setConfirm(e.target.value)} /><button className="danger-button" onClick={remove} disabled={confirm !== 'DELETE'}><Trash2 className="w-4 mr-2" /> Delete permanently</button></div></section>
    {message && <p className="surface !shadow-none p-3 mt-4">{message}</p>}
  </div>
}
